# Generated by Django 6.0 on 2025-12-27 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('bkash', 'bKash')], db_index=True, help_text='Payment provider (stripe/bkash)', max_length=20)),
                ('transaction_id', models.CharField(db_index=True, help_text='Unique transaction ID from payment provider', max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10)),
                ('currency', models.CharField(default='USD', help_text='Currency code (USD, BDT, etc.)', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('raw_response', models.JSONField(blank=True, default=dict, help_text='Raw JSON response from payment provider')),
                ('error_message', models.TextField(blank=True, help_text='Error message if payment failed')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the payment')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_id'], name='payments_transac_a1f824_idx'), models.Index(fields=['provider', 'status'], name='payments_provide_2bfd66_idx'), models.Index(fields=['order', 'status'], name='payments_order_i_3d4604_idx'), models.Index(fields=['created_at'], name='payments_created_e3a130_idx')],
            },
        ),
    ]
